import { Icon } from "../Icon";
import "./About.css";
import ApeMobile_1x from "../../assets/main-ape-2-mobile-1x.png";
import ApeMobile_2x from "../../assets/main-ape-2-mobile-2x.png";
import ApeTablet_1x from "../../assets/main-ape-2-tablet-1x.png";
import ApeTablet_2x from "../../assets/main-ape-2-tablet-2x.png";
import ApeDesktop_1x from "../../assets/main-ape-2-desktop-1x.png";
import ApeDesktop_2x from "../../assets/main-ape-2-desktop-2x.png";

interface InfoProps {
  widthScreen: number;
}

export const Info: React.FC<InfoProps> = ({ widthScreen }) => {
  let iconSize: number = 24;
  if (widthScreen >= 1440) {
    iconSize = 36;
  }

  return (
    <section className="info-section">
      <div className="info-section-part-one">
        {widthScreen >= 768 ? (
          <h2 className="info-title">
            A STORY <br />
            THAT STARTED WITH <span className="title-span">ONE SIMPLE APE</span>
          </h2>
        ) : (
          <h2 className="info-title">
            A STORY THAT STARTED WITH{" "}
            <span className="title-span">
              {" "}
              ONE <br />
              SIMPLE <br />
              APE
            </span>
          </h2>
        )}
        {widthScreen >= 768 ? (
          <p className="info-text-one">
            WHO GOT FED UP WITH BORING <br />
            AND HYPOCRITIC COMMONPLACE THIS IS HOW THE IDEA OF ESCAPING AND
            DYNAMIC JOURNEY ON THE <br />
            YACHT
          </p>
        ) : (
          <p className="info-text-one">
            WHO GOT <br />
            FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE IDEA
            OF ESCAPING AND DYNAMIC JOURNEY ON THE YACHT
          </p>
        )}
      </div>
      <div className="info-section-part-two">
        <p className="info-text-two">
          <Icon name="icon-add-sharp" size={iconSize} />
          <span className="span-info-text-two">
            EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS
            ARE RANDOMLY GENERATED BY USERS
          </span>
        </p>
        <picture className="picture-ape">
          <source
            srcSet={`${ApeMobile_1x}, ${ApeMobile_2x} 2x`}
            media="(max-width: 743px)"
          />
          <source
            srcSet={`${ApeTablet_1x}, ${ApeTablet_2x} 2x `}
            media="(min-width: 744px) and (max-width: 1439px)"
          />
          <source
            media="(min-width: 1440px)"
            srcSet={`${ApeDesktop_1x}, ${ApeDesktop_2x} 2x`}
          />
          <img src={ApeMobile_1x} alt="illustration ape" />
        </picture>
      </div>
    </section>
  );
};
